version: '3'

services:
  api:
    image: 459648971904.dkr.ecr.ap-northeast-1.amazonaws.com/freestudy-api:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080

  local-db:
    image: postgres
    container_name: event_api_local_db
    ports:
    - 5432:5432
    env_file:
      - env.db
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"



