version: '3'

services:
  api:
    image: 459648971904.dkr.ecr.ap-northeast-1.amazonaws.com/freestudy-api:latest
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
