<<<<<<< HEAD
management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      show-details: always
=======
>>>>>>> 02d5bad... Change index controller text for deploying change checking
